/**
 * 数据导出器
 * @module modules/fire/DataExporter
 * @description 支持多种格式的数据导出
 * 参考: ForeFire 多格式输出
 */

class DataExporter {
  constructor() {
    this.version = '3.0.0';
  }

  exportGeoJSON(engine, options = {}) {
    const boundary = engine.getBoundary();
    const statistics = engine.getStatistics();
    
    if (!boundary || boundary.length < 3) {
      return null;
    }
    
    const coordinates = boundary.map(p => [p.lon, p.lat]);
    coordinates.push(coordinates[0]);
    
    const feature = {
      type: 'Feature',
      geometry: {
        type: 'Polygon',
        coordinates: [coordinates]
      },
      properties: {
        burnedArea: statistics.burnedArea,
        perimeter: statistics.perimeter,
        maxSpreadRate: statistics.maxSpreadRate,
        maxIntensity: statistics.maxIntensity,
        iteration: engine._iteration || 0,
        timestamp: new Date().toISOString()
      }
    };
    
    if (options.includeHistory && engine.getHistory) {
      const history = engine.getHistory();
      feature.properties.history = history;
    }
    
    return {
      type: 'FeatureCollection',
      features: [feature],
      metadata: {
        source: 'FireSpreadEngineV3',
        version: this.version,
        crs: {
          type: 'name',
          properties: {
            name: 'EPSG:4326'
          }
        }
      }
    };
  }

  exportGeoJSONTimeSeries(engine, options = {}) {
    const history = engine.getHistory ? engine.getHistory() : [];
    
    if (history.length === 0) {
      return this.exportGeoJSON(engine, options);
    }
    
    const features = history.map((snapshot, index) => {
      const coordinates = snapshot.boundary.map(p => [p.lon, p.lat]);
      if (coordinates.length > 0) {
        coordinates.push(coordinates[0]);
      }
      
      return {
        type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [coordinates]
        },
        properties: {
          time: index,
          burnedArea: snapshot.burnedArea,
          perimeter: snapshot.perimeter,
          timestamp: snapshot.timestamp || new Date().toISOString()
        }
      };
    });
    
    return {
      type: 'FeatureCollection',
      features,
      metadata: {
        source: 'FireSpreadEngineV3',
        version: this.version,
        temporal: true
      }
    };
  }

  exportKML(engine, options = {}) {
    const boundary = engine.getBoundary();
    const statistics = engine.getStatistics();
    
    if (!boundary || boundary.length < 3) {
      return null;
    }
    
    const coordinates = boundary.map(p => 
      `${p.lon},${p.lat},0`
    ).join(' ');
    
    const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Fire Simulation Result</name>
    <description>Generated by FireSpreadEngineV3</description>
    <Style id="fireStyle">
      <LineStyle>
        <color>ff0000ff</color>
        <width>2</width>
      </LineStyle>
      <PolyStyle>
        <color>7fff0000</color>
        <fill>1</fill>
        <outline>1</outline>
      </PolyStyle>
    </Style>
    <Placemark>
      <name>Fire Boundary</name>
      <description>
        <![CDATA[
          <h3>Fire Statistics</h3>
          <ul>
            <li>Burned Area: ${(statistics.burnedArea / 1000000).toFixed(2)} km²</li>
            <li>Perimeter: ${(statistics.perimeter / 1000).toFixed(2)} km</li>
            <li>Max Spread Rate: ${statistics.maxSpreadRate.toFixed(2)} m/s</li>
          </ul>
        ]]>
      </description>
      <styleUrl>#fireStyle</styleUrl>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${coordinates}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>
  </Document>
</kml>`;
    
    return kml;
  }

  exportKMLTimeSeries(engine, options = {}) {
    const history = engine.getHistory ? engine.getHistory() : [];
    
    if (history.length === 0) {
      return this.exportKML(engine, options);
    }
    
    let placemarks = '';
    
    history.forEach((snapshot, index) => {
      if (!snapshot.boundary || snapshot.boundary.length < 3) return;
      
      const coordinates = snapshot.boundary.map(p => 
        `${p.lon},${p.lat},0`
      ).join(' ');
      
      const opacity = Math.floor(128 + (127 * index / history.length)).toString(16).padStart(2, '0');
      
      placemarks += `
    <Placemark>
      <name>Fire at T=${index}</name>
      <TimeStamp>
        <when>${snapshot.timestamp || new Date(Date.now() + index * 60000).toISOString()}</when>
      </TimeStamp>
      <Style>
        <PolyStyle>
          <color>${opacity}ff0000</color>
        </PolyStyle>
      </Style>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${coordinates}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>`;
    });
    
    return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Fire Simulation Time Series</name>
    <description>Generated by FireSpreadEngineV3</description>
    ${placemarks}
  </Document>
</kml>`;
  }

  exportNetCDF(engine, options = {}) {
    const header = this._createNetCDFHeader(engine, options);
    const data = this._createNetCDFData(engine);
    
    return {
      header,
      data,
      toBuffer: () => this._serializeNetCDF(header, data)
    };
  }

  _createNetCDFHeader(engine, options) {
    const { width, height } = engine.dem || { width: 100, height: 100 };
    
    return {
      dimensions: {
        time: 1,
        x: width,
        y: height,
        nv: 2
      },
      variables: {
        time: {
          type: 'double',
          dimensions: ['time'],
          attributes: {
            units: 'seconds since 1970-01-01',
            long_name: 'time'
          }
        },
        x: {
          type: 'double',
          dimensions: ['x'],
          attributes: {
            units: 'degrees_east',
            long_name: 'longitude'
          }
        },
        y: {
          type: 'double',
          dimensions: ['y'],
          attributes: {
            units: 'degrees_north',
            long_name: 'latitude'
          }
        },
        fire_state: {
          type: 'byte',
          dimensions: ['time', 'y', 'x'],
          attributes: {
            long_name: 'fire state',
            flag_values: [0, 1],
            flag_meanings: 'unburned burned'
          }
        },
        spread_rate: {
          type: 'float',
          dimensions: ['time', 'y', 'x'],
          attributes: {
            units: 'm/s',
            long_name: 'fire spread rate'
          }
        },
        intensity: {
          type: 'float',
          dimensions: ['time', 'y', 'x'],
          attributes: {
            units: '1',
            long_name: 'fire intensity'
          }
        }
      },
      globalAttributes: {
        title: 'Wildfire Simulation Output',
        source: 'FireSpreadEngineV3',
        version: this.version,
        Conventions: 'CF-1.8',
        history: `Created ${new Date().toISOString()}`
      }
    };
  }

  _createNetCDFData(engine) {
    return {
      time: [Date.now() / 1000],
      x: engine.getXCoordinates ? engine.getXCoordinates() : [],
      y: engine.getYCoordinates ? engine.getYCoordinates() : [],
      fire_state: engine.fireGrid ? this._convertToByte(engine.fireGrid) : [],
      spread_rate: engine.spreadRateGrid || [],
      intensity: engine.intensityGrid || []
    };
  }

  _convertToByte(floatArray) {
    const result = new Uint8Array(floatArray.length);
    for (let i = 0; i < floatArray.length; i++) {
      result[i] = floatArray[i] >= 0 && floatArray[i] < 1000 ? 1 : 0;
    }
    return result;
  }

  _serializeNetCDF(header, data) {
    const parts = [];
    
    parts.push(new Uint8Array([0x43, 0x44, 0x46, 0x01]));
    
    const numDims = Object.keys(header.dimensions).length;
    parts.push(new Uint8Array(new Int32Array([0, numDims]).buffer));
    
    Object.entries(header.dimensions).forEach(([name, size]) => {
      parts.push(this._encodeString(name));
      parts.push(new Uint8Array(new Int32Array([size]).buffer));
    });
    
    return this._concatenateArrayBuffers(parts);
  }

  _encodeString(str) {
    const encoded = new TextEncoder().encode(str);
    const padding = (4 - (encoded.length % 4)) % 4;
    const result = new Uint8Array(4 + encoded.length + padding);
    
    new Uint32Array(result.buffer, 0, 1)[0] = encoded.length;
    result.set(encoded, 4);
    
    return result;
  }

  _concatenateArrayBuffers(arrays) {
    const totalLength = arrays.reduce((sum, arr) => sum + arr.length, 0);
    const result = new Uint8Array(totalLength);
    let offset = 0;
    
    for (const arr of arrays) {
      result.set(arr, offset);
      offset += arr.length;
    }
    
    return result;
  }

  exportCSV(engine, options = {}) {
    const boundary = engine.getBoundary();
    const statistics = engine.getStatistics();
    
    let csv = 'lon,lat,intensity,time\n';
    
    if (boundary) {
      boundary.forEach(p => {
        csv += `${p.lon},${p.lat},${p.intensity || 0},${p.time || 0}\n`;
      });
    }
    
    csv += '\n# Statistics\n';
    csv += `# Burned Area,${statistics.burnedArea}\n`;
    csv += `# Perimeter,${statistics.perimeter}\n`;
    csv += `# Max Spread Rate,${statistics.maxSpreadRate}\n`;
    
    return csv;
  }

  exportWKT(engine, options = {}) {
    const boundary = engine.getBoundary();
    
    if (!boundary || boundary.length < 3) {
      return null;
    }
    
    const coordinates = boundary.map(p => `${p.lon} ${p.lat}`).join(', ');
    
    return `POLYGON((${coordinates}))`;
  }

  download(data, filename, mimeType) {
    let blob;
    
    if (typeof data === 'string') {
      blob = new Blob([data], { type: mimeType });
    } else if (data instanceof ArrayBuffer || ArrayBuffer.isView(data)) {
      blob = new Blob([data], { type: mimeType });
    } else {
      blob = new Blob([JSON.stringify(data, null, 2)], { type: mimeType });
    }
    
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  downloadGeoJSON(engine, filename = 'fire_simulation.geojson') {
    const data = this.exportGeoJSON(engine);
    if (data) {
      this.download(data, filename, 'application/geo+json');
    }
  }

  downloadKML(engine, filename = 'fire_simulation.kml') {
    const data = this.exportKML(engine);
    if (data) {
      this.download(data, filename, 'application/vnd.google-earth.kml+xml');
    }
  }

  downloadCSV(engine, filename = 'fire_simulation.csv') {
    const data = this.exportCSV(engine);
    this.download(data, filename, 'text/csv');
  }
}

export default DataExporter;
